repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: uv run ruff check --fix
        language: system
        types: [python]
        require_serial: true
      - id: ruff-format
        name: ruff-format
        entry: uv run ruff format
        language: system
        types: [python]
        require_serial: true

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: uv run pytest -x --tb=short
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-push]
        verbose: true