site_name: Quaestor
site_description: A minimal Claude Code plugin for specification-driven development
site_author: Jean Luciano
site_url: https://jeanluciano.github.io/quaestor

repo_name: jeanluciano/quaestor
repo_url: https://github.com/jeanluciano/quaestor

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quickstart.md
    - Configuration: getting-started/configuration.md
  - Skills:
    - Overview: skills/overview.md
  - Commands:
    - /plan: commands/plan.md
    - /implement: commands/impl.md
    - /research: commands/research.md
  - Specification-Driven Development:
    - Overview: specs/overview.md
    - Creating Specifications: specs/creating.md
    - Implementation Workflow: specs/workflow.md
  - Sub-Agents:
    - Overview: agents/overview.md
    - Planner: agents/planner.md
    - Architect: agents/architect.md
    - Implementer: agents/implementer.md
    - QA: agents/qa.md
    - Researcher: agents/researcher.md
    - Security: agents/security.md
    - Reviewer: agents/reviewer.md
    - Debugger: agents/debugger.md
    - Refactorer: agents/refactorer.md
    - Workflow Coordinator: agents/workflow-coordinator.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/jeanluciano/quaestor
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/quaestor/

copyright: Copyright &copy; 2024 Jean Luciano